package auth

import (
	"bytes"
	"encoding/base64"
	"strings"
	"testing"
)

func TestSecretGeneratorProducesThirtyTwoRandomBytes(t *testing.T) {
	source := bytes.NewReader(bytes.Repeat([]byte{0xA5}, 32))
	generator := NewSecretGenerator(source, 32)

	secret, err := generator.Generate()
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	raw, err := base64.RawURLEncoding.DecodeString(secret)
	if err != nil {
		t.Fatalf("generated secret is not base64url: %v", err)
	}
	if len(raw) != 32 {
		t.Fatalf("generated bytes = %d, want 32", len(raw))
	}
	if !bytes.Equal(raw, bytes.Repeat([]byte{0xA5}, 32)) {
		t.Fatal("Generate() did not consume the supplied random source")
	}
}

func TestSecretGeneratorRejectsInsufficientEntropy(t *testing.T) {
	if _, err := NewSecretGenerator(bytes.NewReader(nil), 15).Generate(); err == nil {
		t.Fatal("Generate() error = nil, want minimum entropy error")
	}
}

func TestPasswordHasherRoundTripAndRehashPolicy(t *testing.T) {
	parameters := Parameters{
		MemoryKiB:   8 * 1024,
		Iterations:  1,
		Parallelism: 1,
		SaltLength:  16,
		KeyLength:   32,
	}
	hasher := NewPasswordHasher(parameters, bytes.NewReader(bytes.Repeat([]byte{0x3C}, 64)))

	encoded, err := hasher.Hash("correct horse battery staple")
	if err != nil {
		t.Fatalf("Hash() error = %v", err)
	}
	if !strings.HasPrefix(encoded, "$argon2id$v=19$") {
		t.Fatalf("encoded hash = %q, want Argon2id PHC format", encoded)
	}

	match, needsRehash, err := hasher.Verify(encoded, "correct horse battery staple")
	if err != nil {
		t.Fatalf("Verify() error = %v", err)
	}
	if !match || needsRehash {
		t.Fatalf("Verify() = match %v, needsRehash %v", match, needsRehash)
	}

	match, _, err = hasher.Verify(encoded, "wrong password")
	if err != nil {
		t.Fatalf("Verify(wrong) error = %v", err)
	}
	if match {
		t.Fatal("Verify(wrong) match = true")
	}

	stronger := NewPasswordHasher(Parameters{
		MemoryKiB:   parameters.MemoryKiB * 2,
		Iterations:  parameters.Iterations,
		Parallelism: parameters.Parallelism,
		SaltLength:  parameters.SaltLength,
		KeyLength:   parameters.KeyLength,
	}, bytes.NewReader(bytes.Repeat([]byte{0x7A}, 32)))
	match, needsRehash, err = stronger.Verify(encoded, "correct horse battery staple")
	if err != nil {
		t.Fatalf("Verify(stronger policy) error = %v", err)
	}
	if !match || !needsRehash {
		t.Fatalf("Verify(stronger policy) = match %v, needsRehash %v", match, needsRehash)
	}
}

func TestPasswordHasherRejectsMalformedEncoding(t *testing.T) {
	hasher := NewPasswordHasher(testParameters(), bytes.NewReader(bytes.Repeat([]byte{1}, 32)))
	if _, _, err := hasher.Verify("not-a-password-hash", "password"); err == nil {
		t.Fatal("Verify() error = nil, want malformed hash error")
	}
}

func testParameters() Parameters {
	return Parameters{
		MemoryKiB:   8 * 1024,
		Iterations:  1,
		Parallelism: 1,
		SaltLength:  16,
		KeyLength:   32,
	}
}
